// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	model "ygodraft/backend/model"

	mock "github.com/stretchr/testify/mock"
)

// DraftQueryGenerator is an autogenerated mock type for the DraftQueryGenerator type
type DraftQueryGenerator struct {
	mock.Mock
}

// InsertDraft provides a mock function with given fields: challengerID, receiverID, settings
func (_m *DraftQueryGenerator) InsertDraft(challengerID int, receiverID int, settings model.DraftSettings) (string, error) {
	ret := _m.Called(challengerID, receiverID, settings)

	if len(ret) == 0 {
		panic("no return value specified for InsertDraft")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, model.DraftSettings) (string, error)); ok {
		return rf(challengerID, receiverID, settings)
	}
	if rf, ok := ret.Get(0).(func(int, int, model.DraftSettings) string); ok {
		r0 = rf(challengerID, receiverID, settings)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, int, model.DraftSettings) error); ok {
		r1 = rf(challengerID, receiverID, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertDraftRound provides a mock function with given fields: draftID, roundNumber, status
func (_m *DraftQueryGenerator) InsertDraftRound(draftID int, roundNumber int, status model.DraftRoundStatus) (string, error) {
	ret := _m.Called(draftID, roundNumber, status)

	if len(ret) == 0 {
		panic("no return value specified for InsertDraftRound")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, model.DraftRoundStatus) (string, error)); ok {
		return rf(draftID, roundNumber, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, model.DraftRoundStatus) string); ok {
		r0 = rf(draftID, roundNumber, status)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, int, model.DraftRoundStatus) error); ok {
		r1 = rf(draftID, roundNumber, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertDraftRoundDeck provides a mock function with given fields: roundID, userID, deck
func (_m *DraftQueryGenerator) InsertDraftRoundDeck(roundID int, userID int, deck []string) (string, error) {
	ret := _m.Called(roundID, userID, deck)

	if len(ret) == 0 {
		panic("no return value specified for InsertDraftRoundDeck")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, []string) (string, error)); ok {
		return rf(roundID, userID, deck)
	}
	if rf, ok := ret.Get(0).(func(int, int, []string) string); ok {
		r0 = rf(roundID, userID, deck)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, int, []string) error); ok {
		r1 = rf(roundID, userID, deck)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDraft provides a mock function with given fields: draftID
func (_m *DraftQueryGenerator) SelectDraft(draftID int) (string, error) {
	ret := _m.Called(draftID)

	if len(ret) == 0 {
		panic("no return value specified for SelectDraft")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(draftID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(draftID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(draftID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDraftsWithStatus provides a mock function with given fields: userID, status
func (_m *DraftQueryGenerator) SelectDraftsWithStatus(userID int, status model.DraftStatus) (string, error) {
	ret := _m.Called(userID, status)

	if len(ret) == 0 {
		panic("no return value specified for SelectDraftsWithStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, model.DraftStatus) (string, error)); ok {
		return rf(userID, status)
	}
	if rf, ok := ret.Get(0).(func(int, model.DraftStatus) string); ok {
		r0 = rf(userID, status)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, model.DraftStatus) error); ok {
		r1 = rf(userID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDraftsWithUsersAndStatus provides a mock function with given fields: userID, user2ID, status
func (_m *DraftQueryGenerator) SelectDraftsWithUsersAndStatus(userID int, user2ID int, status model.DraftStatus) (string, error) {
	ret := _m.Called(userID, user2ID, status)

	if len(ret) == 0 {
		panic("no return value specified for SelectDraftsWithUsersAndStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, model.DraftStatus) (string, error)); ok {
		return rf(userID, user2ID, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, model.DraftStatus) string); ok {
		r0 = rf(userID, user2ID, status)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, int, model.DraftStatus) error); ok {
		r1 = rf(userID, user2ID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDraft provides a mock function with given fields: draftID, status
func (_m *DraftQueryGenerator) UpdateDraft(draftID int, status model.DraftStatus) (string, error) {
	ret := _m.Called(draftID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDraft")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, model.DraftStatus) (string, error)); ok {
		return rf(draftID, status)
	}
	if rf, ok := ret.Get(0).(func(int, model.DraftStatus) string); ok {
		r0 = rf(draftID, status)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, model.DraftStatus) error); ok {
		r1 = rf(draftID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDraftRound provides a mock function with given fields: draftRoundID, winnerID, status
func (_m *DraftQueryGenerator) UpdateDraftRound(draftRoundID int, winnerID int, status model.DraftRoundStatus) (string, error) {
	ret := _m.Called(draftRoundID, winnerID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDraftRound")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, model.DraftRoundStatus) (string, error)); ok {
		return rf(draftRoundID, winnerID, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, model.DraftRoundStatus) string); ok {
		r0 = rf(draftRoundID, winnerID, status)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, int, model.DraftRoundStatus) error); ok {
		r1 = rf(draftRoundID, winnerID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDraftQueryGenerator creates a new instance of DraftQueryGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDraftQueryGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *DraftQueryGenerator {
	mock := &DraftQueryGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
