// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	model "ygodraft/backend/model"

	mock "github.com/stretchr/testify/mock"
)

// DraftClient is an autogenerated mock type for the DraftClient type
type DraftClient struct {
	mock.Mock
}

// AcceptDraftChallenge provides a mock function with given fields: draftID, userID
func (_m *DraftClient) AcceptDraftChallenge(draftID int, userID int) error {
	ret := _m.Called(draftID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptDraftChallenge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(draftID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDraftChallenge provides a mock function with given fields: challengerID, receiverID, settings
func (_m *DraftClient) CreateDraftChallenge(challengerID int, receiverID int, settings model.DraftSettings) error {
	ret := _m.Called(challengerID, receiverID, settings)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraftChallenge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, model.DraftSettings) error); ok {
		r0 = rf(challengerID, receiverID, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineDraftChallenge provides a mock function with given fields: draftID, userID
func (_m *DraftClient) DeclineDraftChallenge(draftID int, userID int) error {
	ret := _m.Called(draftID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeclineDraftChallenge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(draftID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDraft provides a mock function with given fields: draftID
func (_m *DraftClient) GetDraft(draftID int) (model.Draft, error) {
	ret := _m.Called(draftID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraft")
	}

	var r0 model.Draft
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Draft, error)); ok {
		return rf(draftID)
	}
	if rf, ok := ret.Get(0).(func(int) model.Draft); ok {
		r0 = rf(draftID)
	} else {
		r0 = ret.Get(0).(model.Draft)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(draftID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDraftsWithStatus provides a mock function with given fields: userID, status
func (_m *DraftClient) GetDraftsWithStatus(userID int, status model.DraftStatus) ([]model.Draft, error) {
	ret := _m.Called(userID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftsWithStatus")
	}

	var r0 []model.Draft
	var r1 error
	if rf, ok := ret.Get(0).(func(int, model.DraftStatus) ([]model.Draft, error)); ok {
		return rf(userID, status)
	}
	if rf, ok := ret.Get(0).(func(int, model.DraftStatus) []model.Draft); ok {
		r0 = rf(userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Draft)
		}
	}

	if rf, ok := ret.Get(1).(func(int, model.DraftStatus) error); ok {
		r1 = rf(userID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SurrenderRunningDraft provides a mock function with given fields: draftID, surrenderingUserID
func (_m *DraftClient) SurrenderRunningDraft(draftID int, surrenderingUserID int) error {
	ret := _m.Called(draftID, surrenderingUserID)

	if len(ret) == 0 {
		panic("no return value specified for SurrenderRunningDraft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(draftID, surrenderingUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserHaveDraftWithStatus provides a mock function with given fields: user1ID, user2ID, status
func (_m *DraftClient) UserHaveDraftWithStatus(user1ID int, user2ID int, status model.DraftStatus) (bool, error) {
	ret := _m.Called(user1ID, user2ID, status)

	if len(ret) == 0 {
		panic("no return value specified for UserHaveDraftWithStatus")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, model.DraftStatus) (bool, error)); ok {
		return rf(user1ID, user2ID, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, model.DraftStatus) bool); ok {
		r0 = rf(user1ID, user2ID, status)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int, model.DraftStatus) error); ok {
		r1 = rf(user1ID, user2ID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDraftClient creates a new instance of DraftClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDraftClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *DraftClient {
	mock := &DraftClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
