// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	model "ygodraft/backend/model"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// CardSaver is an autogenerated mock type for the CardSaver type
type CardSaver struct {
	mock.Mock
}

// SaveAllCards provides a mock function with given fields: cards
func (_m *CardSaver) SaveAllCards(cards *[]*model.Card) error {
	ret := _m.Called(cards)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]*model.Card) error); ok {
		r0 = rf(cards)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveCard provides a mock function with given fields: card
func (_m *CardSaver) SaveCard(card *model.Card) error {
	ret := _m.Called(card)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Card) error); ok {
		r0 = rf(card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCardSaver creates a new instance of CardSaver. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewCardSaver(t testing.TB) *CardSaver {
	mock := &CardSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
