// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	model "ygodraft/backend/model"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// CardSetSaver is an autogenerated mock type for the CardSetSaver type
type CardSetSaver struct {
	mock.Mock
}

// SaveSets provides a mock function with given fields: cards
func (_m *CardSetSaver) SaveSets(cards []model.CardSet) error {
	ret := _m.Called(cards)

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.CardSet) error); ok {
		r0 = rf(cards)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCardSetSaver creates a new instance of CardSetSaver. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewCardSetSaver(t testing.TB) *CardSetSaver {
	mock := &CardSetSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
