// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// JsonWebClient is an autogenerated mock type for the JsonWebClient type
type JsonWebClient struct {
	mock.Mock
}

// GetJsonFromTarget provides a mock function with given fields: targetUrl, data
func (_m *JsonWebClient) GetJsonFromTarget(targetUrl string, data interface{}) error {
	ret := _m.Called(targetUrl, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(targetUrl, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJsonWebClient creates a new instance of JsonWebClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewJsonWebClient(t testing.TB) *JsonWebClient {
	mock := &JsonWebClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
